### PR TITLE
Add back-button

### LINKED ISSUE #8: Add a back-button
Would make it a lot easier to use the app when clicking around in profiles.

I tried adding a simple one that just goes back in history but the scroll position got reset which was annoying.

### PR DESCRIPTION
**Pull request by Powersource**
Closes https://github.com/AljoschaMeyer/hacky-art/issues/8

Doesn't maintain scroll position but goes back :man_shrugging:

### CODE REVIEW

**Comment by Powersource** [comment]
@AljoschaMeyer

**Comment by AljoschaMeyer** [comment]
@Powersource 
Choo has its own routing logic, see [here](https://choo.io/docs/routing). There's a section on "Programmatic Navigation" that includes an example for a back button. Just call `emit('popState')`. Do you want to update the PR, or should I implement this?

**Comment by Powersource** [comment]
I'll update it later today :)

**Comment by Powersource** [comment]
Hmm, since nav is called like `nav({ me: state.ssb.id })`, when I try to use `emit` in there, it just says that `emit` is undefined. I'm used to that getting passed in by the routing (like in the docs you linked), is passing it in manually also considered a good idea? (I really don't know :P ) I'll pass it manually for now at least.

**Comment by Powersource** [comment]
Oh yeah wait nav is only part of a page ugh now I'm confused about what would be best practice haha.

**Comment by Powersource** [comment]
Ok so I did all that however nothing happens when I popState ¯\\\_(ツ)\_/¯

**Comment by Powersource** [comment]
Ok lol that documentation is apparently out of date, https://github.com/choojs/choo/issues/621, we [should be using](https://github.com/choojs/choo#popstatestateeventspopstate) `history.go(-1)` for this

**Comment by Powersource** [comment]
Fixed the code and opened an issue https://github.com/choojs/website/issues/75 about the docs.

**Comment by AljoschaMeyer** [comment]
Huh, so your first commit actually did the right thing. Sorry about that. Is there anything left to do here, or can I merge at this point?

**Comment by Powersource** [comment]
I think you can merge.

Jacob

**Comment by AljoschaMeyer** [comment]
Great, thanks for figuring this out.

That's some #premium content you published there btw :smile:

**Pull request merged**
