### PR TITLE
Style Adjustment to Home Page

### PR DESCRIPTION
**Pull request by zachmandeville**
This pull request brings in some simple styling to the home page and makes the views for the page a little bit more semantic.

On the CSS side, I brought in a custom font ([iaWriter Quattro](https://github.com/iaolo/iA-Fonts/tree/master/iA%20Writer%20Quattro)) and brought in a bit of color to reduce glare and increase accessibility.

On the views side, I rearranged the elements (image comes first, and then the title, author, and description) and then refashioned the HTML to be more semantic and accessible. For example, I replaced the div within each item to be a [<figure>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure), and the text to all be contained in a [<figcaption>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption).  I upgraded the h4 of the title to be an h2 as that fit the document outline better.

I tried to stay consistent with the style conventions you established for class names and the layout of your views.  If there's anywhere I overtreaded, it was unintentional and I apologize!

### CODE REVIEW

**Comment by zachmandeville** [comment]
Oh! And one more thing!  In https://github.com/AljoschaMeyer/hacky-art/pull/3/commits/32132a8f330832a45ef922d983bdd07ea5a9e961, I commented out the preview and publish stores, and views, from main.js as I couldn't find the files they were referencing.  Were they removed from `stores/`, or am I dense and missed something?

**Comment by AljoschaMeyer** [comment]
@zachmandeville Did you pull in all changes? Your [repo](https://github.com/zachmandeville/hacky-art) is 15 commits behind master, which might be why the new views are missing for you.

**Comment by AljoschaMeyer** [comment]
Wait no, I looked at the wrong branch...

I forgot to `git add` those files, they are pushed now.

**Comment by AljoschaMeyer** [comment]
@zachmandeville `npm i` just finished, so I could finally take a look. It's a thing of beauty! :green_heart:
I'll fix the file derps after merging this in. Git surely has more clever ways for doing this, but I don't care and I want this merged!

**Pull request merged**
